pipeline {
   environment {
     FOO = "foo"
   }

   agent any
   stages {
       stage("first") {
           steps {
               sh "echo ${FOO}"
               sh "ls -a"
               sh "pwd"
               cd backend
               which docker
               which docker-compose
               docker stop $(docker ps -a -q)
               docker rm $(docker ps -a -q)
               docker rmi $(docker images -q)
               cd backend
               docker-compose build
           }
       }
   }
}